# Generated by Django 4.1 on 2022-08-24 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('patient_insurance_type', models.CharField(choices=[('0', 'Without Insurance'), ('1', 'Medicaid'), ('2', 'Medicare'), ('3', 'Private')], default='0', max_length=20)),
                ('patient_preexisting_conditions', models.TextField(max_length=80)),
                ('patient_current_medications', models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_blurb', models.CharField(max_length=200)),
                ('provider_specialization', models.CharField(choices=[('0', 'None'), ('1', 'Cardiology'), ('2', 'Neurology'), ('3', 'Pediatrics'), ('4', 'Surgery'), ('5', 'Dental'), ('6', 'General Medicine'), ('7', 'Psychiatry'), ('8', 'Radiology'), ('9', 'Surgical'), ('10', 'Other')], default='0', max_length=20)),
                ('insurances_taken', models.CharField(choices=[('0', 'Without Insurance'), ('1', 'Medicaid'), ('2', 'Medicare'), ('3', 'Private')], default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedulerfavoritefood', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_scheduler', models.BooleanField(default=False)),
                ('is_provider', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('0', 'Awating Response'), ('1', 'Accepted'), ('2', 'Rejected'), ('3', 'Cancelled'), ('4', 'Completed')], default='0', max_length=20)),
                ('ailment_category', models.CharField(choices=[('0', 'None'), ('1', 'Cardiology'), ('2', 'Neurology'), ('3', 'Pediatrics'), ('4', 'Surgery'), ('5', 'Dental'), ('6', 'General Medicine'), ('7', 'Psychiatry'), ('8', 'Radiology'), ('9', 'Surgical'), ('10', 'Other')], default='0', max_length=20)),
                ('ailment_description', models.CharField(max_length=80)),
                ('preferred_date_range', models.DateField()),
                ('procedure_date', models.DateField()),
                ('scheduling_comment', models.TextField()),
                ('doctor_comment_on_operation', models.TextField()),
                ('doctorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
                ('schedulerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
