# Generated by Django 4.1 on 2022-08-25 21:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_scheduler', models.BooleanField(default=False)),
                ('is_provider', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedulerProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_personal_blurb', models.CharField(max_length=200)),
                ('provider_specialization', models.CharField(choices=[('0', 'None'), ('1', 'Cardiology'), ('2', 'Neurology'), ('3', 'Pediatrics'), ('4', 'Surgery'), ('5', 'Dental'), ('6', 'General Medicine'), ('7', 'Psychiatry'), ('8', 'Radiology'), ('9', 'Surgical'), ('10', 'Other')], default='0', max_length=20)),
                ('provider_insurances_taken', models.CharField(choices=[('0', 'Without Insurance'), ('1', 'Medicaid'), ('2', 'Medicare'), ('3', 'Private')], default='0', max_length=20)),
                ('day1', models.BooleanField(default=False)),
                ('day2', models.BooleanField(default=False)),
                ('day3', models.BooleanField(default=False)),
                ('day4', models.BooleanField(default=False)),
                ('day5', models.BooleanField(default=False)),
                ('day6', models.BooleanField(default=False)),
                ('day7', models.BooleanField(default=False)),
                ('providerProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('0', 'Awating Response'), ('1', 'Accepted'), ('2', 'Rejected'), ('3', 'Completed')], default='0', max_length=20)),
                ('request_ailment_category', models.CharField(choices=[('0', 'None'), ('1', 'Cardiology'), ('2', 'Neurology'), ('3', 'Pediatrics'), ('4', 'Surgery'), ('5', 'Dental'), ('6', 'General Medicine'), ('7', 'Psychiatry'), ('8', 'Radiology'), ('9', 'Surgical'), ('10', 'Other')], default='0', max_length=20)),
                ('request_ailment_description', models.CharField(max_length=80)),
                ('request_preferred_date_range_start', models.DateField()),
                ('request_preferred_date_range_end', models.DateField()),
                ('request_procedure_date', models.DateField()),
                ('request_scheduling_comment', models.TextField(default=None)),
                ('request_doctor_comment_on_operation', models.TextField(default=None)),
                ('request_doctor_profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='doctorofrequest', to=settings.AUTH_USER_MODEL)),
                ('request_patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientofrequest', to=settings.AUTH_USER_MODEL)),
                ('request_scheduler_profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='schedulerofrequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_age', models.IntegerField()),
                ('patient_insurance_type', models.CharField(choices=[('0', 'Without Insurance'), ('1', 'Medicaid'), ('2', 'Medicare'), ('3', 'Private')], default='0', max_length=20)),
                ('patient_preexisting_conditions', models.TextField(max_length=80)),
                ('patient_current_medications', models.TextField(max_length=80)),
                ('patientProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
