# Generated by Django 4.1 on 2022-08-24 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='current_medications',
            new_name='patient_current_medications',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='preexisting_conditions',
            new_name='patient_preexisting_conditions',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='password',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='email',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='password',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='username',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='email',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='password',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='scheduler',
            name='username',
        ),
        migrations.AddField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, default=69, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_insurance_type',
            field=models.CharField(choices=[('0', 'Without Insurance'), ('1', 'Medicaid'), ('2', 'Medicare'), ('3', 'Private')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='id',
            field=models.BigAutoField(auto_created=True, default=420, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='insurances_taken',
            field=models.CharField(choices=[('0', 'Without Insurance'), ('1', 'Medicaid'), ('2', 'Medicare'), ('3', 'Private')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_specialization',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Cardiology'), ('2', 'Neurology'), ('3', 'Pediatrics'), ('4', 'Surgery'), ('5', 'Dental'), ('6', 'General Medicine'), ('7', 'Psychiatry'), ('8', 'Radiology'), ('9', 'Surgical'), ('10', 'Other')], default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='id',
            field=models.BigAutoField(auto_created=True, default=76, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientpersonal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='ailment_category',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Cardiology'), ('2', 'Neurology'), ('3', 'Pediatrics'), ('4', 'Surgery'), ('5', 'Dental'), ('6', 'General Medicine'), ('7', 'Psychiatry'), ('8', 'Radiology'), ('9', 'Surgical'), ('10', 'Other')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='ailment_description',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='doctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='preferred_date_range',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='procedure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='request_status',
            field=models.CharField(choices=[('0', 'Awating Response'), ('1', 'Accepted'), ('2', 'Rejected'), ('3', 'Cancelled'), ('4', 'Completed')], default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrequest',
            name='schedulerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provider',
            name='providerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providerpersonal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='schedulerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulerpersonal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_patient', models.BooleanField(default=False)),
                ('is_scheduler', models.BooleanField(default=False)),
                ('is_provider', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
